### PR TITLE
Add warnings for parameters that were not provided at launch

### PR DESCRIPTION
**Pull request by alain-m**
See https://github.com/savioke/relay-ros/issues/1126 for explanations
Also related to https://github.com/savioke/relay-ros/pull/1125

### CODE REVIEW

**Comment by alain-m** [comment]
It would be prettier to make a templated function to handle all these parameter initializations in a single line for each. Feel free to edit this PR or I can do it tomorrow.
Problems like https://github.com/savioke/relay-ros/issues/1126 could occur on many other nodes and changes to a few parameters may not be caught by regression tests. Having a standard templated function shared by all our packages that throws appropriate warnings/errors/abort when parameters cannot be read might spare us from similar issues in the future. It is what I did in the past.
However we cannot easily share these functions with external packages like slam_karto, so I guess we would need to duplicate a bit of code.

Unless there is some other version of getParam in roscpp that I don't know about ...

**Comment by stwirth** [comment]
Usually using a default parameter is our preferred method and should not throw any warning.

Long time ago I programmed a generic way of loading ROS parameters directly into OpenKarto's ParameterManager. Unfortunately that was for Willow Garage and I didn't upstream the change. I'll check how much work it is and if I can redo it quickly.

**Comment by stwirth** [comment]
Done, it was pretty straight forward: https://github.com/savioke/slam_karto/pull/8.
I would prefer that solution.

**Comment by alain-m** [comment]
https://github.com/savioke/slam_karto/pull/8 looks great, I'll close this PR. As for

> Usually using a default parameter is our preferred method and should not throw any warning

I think it'd be worth revisiting that assumption. What just happened here for slam_karto could happen to other nodes as we move around and refactor code in the future. A simple typo/abbreviation in a launch file is very hard to notice. A simple function wrapped around getParam could help us throw warnings/errors/abort depending on the parameter while keeping the code as concise as before.
The alternative would be to set up regression tests by checking parameter values at runtime, but that seems tedious and hard to maintain.

**Pull request closed without merging**
